version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: goimomi_db
      POSTGRES_USER: goimomi_user
      POSTGRES_PASSWORD: Goimomi@123
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: goimomi-holidays-backend/Dockerfile
    env_file:
      - goimomi-holidays-backend/.env
    depends_on:
      - db
    volumes:
      - ./goimomi-holidays-backend/static:/app/static
      - ./goimomi-holidays-backend/media:/app/media
    ports:
      - "8000:8000"

  frontend:
    build:
      context: goimomi-holidays-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
